baseURL = "https://ysugiyama.netlify.com/"
disqusShortname = ""
languageCode = "ja-jp"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "ysugiyama - Portfolio"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contactFormAction = "#"
copyright = "&copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "This is meta description"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "images/mylogo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/character_program_smart.png"
title = "Do you know ushitapunikia-kun? <br>Yes, I know."
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/yuji.sugiyama.773"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/yuji9511_compro"
[[params.social]]
icon = "ti-github"
link = "https://github.com/ysugiyama12"
